baseURL = "https://impl.dev"
title = "Aimee Zhu"
theme = "hugo-theme-minos"
publishDir = "public"

googleAnalytics = "UA-134203640-1"

paginate = 8
pygmentsUseClasses = true

[params]
smartToc = true
katex = true

[social]
github = "Aimeedeer"

[menu]

  [[menu.main]]
    name = "Posts"
    url = "/posts/"
    weight = -110

  [[menu.main]]
    name = "Coconut Reports"
    url = "/reports/"
    weight = -100
    
  [[menu.main]]
    name = "Study Notes"
    url = "https://study.impl.dev"
    weight = -90

  [[menu.main]]
    name = "rib.rs"
    url = "https://rib.rs"
    weight = -80
    
  [[menu.main]]
    identifier = "about"
    name = "About"
    url = "/about/"
    weight = -70

[module]
  [[module.mounts]]
    source = "content"
    target = "content"

[taxonomies]
  category = "categories"
  tag = "tags"