baseURL = "https://impl.dev"
title = "Aimee.Z"
theme = "hugo-theme-minos"
publishDir = "public"

# (Optional) Set Google Analytics if you use it to track your website.
# Always put it on the top of the configuration file, otherwise it won't work
googleAnalytics = "UA-134203640-1"

paginate = 10


[params]
smartToc = true
katex = true
customCss = ["css/foo.css"]

[social]
github = "Aimeedeer"

[menu]

  [[menu.main]]
    name = "Posts"
    url = "/posts/"
    weight = -110

  [[menu.main]]
    name = "Coconut Reports"
    url = "/reports/"
    weight = -100
    
  [[menu.main]]
    identifier = "about"
    name = "About"
    url = "/about/"
    weight = -90

[module]
  [[module.mounts]]
    source = "content"
    target = "content"