baseURL = "https://impl.dev"
title = "Aimee Zhu's Blog"
theme = "hugo-theme-minos"
publishDir = "public"

googleAnalytics = "UA-134203640-1"

paginate = 8
pygmentsUseClasses = true

[params]
smartToc = true
katex = true

[social]
github = "Aimeedeer"

[menu]

  [[menu.main]]
  name = "Categories"
  url = "/categories"
  weight = -100
    
  [[menu.main]]
    identifier = "about"
    name = "About"
    url = "/about/"
    weight = -90

[module]
  [[module.mounts]]
    source = "content"
    target = "content"

[taxonomies]
  category = "categories"
  tag = "tags"