[build]
publish = "public"
command = "hugo"

[context.production.environment]
HUGO_VERSION = "0.71.1"

[context.deploy-preview.environment]
HUGO_VERSION = "0.71.1"

[[headers]]
   for = "/*"
   [headers.values]
      Access-Control-Allow-Origin = "*"